Added arm64 targets for linux binaries
kubernetes/node-problem-detector pull request #561
Opened 2021-05-19 22:45 UTC by pwschuurman

This change adds support for arm64 targets for the linux binaries and an arm64 tarball target. See #135 

The existing `build-binaries`, `build-tar` targets now compile for arm64 in addition to amd64 on linux.

Thanks to @jeremyje for the multi-platform/os support (#545). It makes this change much simpler.

2021-05-20 00:59 UTC, jeremyje requested changes

2021-05-20 00:59 UTC, jeremyje commented on .travis.yml
> + - sudo apt-get install -y libsystemd-dev gcc-aarch64-linux-gnu
Can you add this to the README.md as well. There are instructions to install libsystemd-dev there.

2021-05-21 01:58 UTC, jeremyje commented
```
GOOS=linux GOARCH=arm64 CGO_ENABLED=1 GO111MODULE=on \
  CC=aarch64-linux-gnu-gcc go build \
	-mod vendor \
	-o output/linux_arm64/bin/node-problem-detector \
	-ldflags '-X k8s.io/node-problem-detector/pkg/version.version=v0.8.8-2-g4690e87' \
	-tags "journald " \
	./cmd/nodeproblemdetector
# runtime/cgo
In file included from /usr/include/stdlib.h:24:0,
                 from _cgo_export.c:3:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
Makefile:167: recipe for target 'output/linux_arm64/bin/node-problem-detector' failed
```

Build Breakage

2021-05-26 03:06 UTC, jeremyje commented
/ok-to-test
/sig node
/priority important-soon

2021-05-26 18:42 UTC, pwschuurman commented
/retest

2021-05-26 22:05 UTC, Random-Liu commented
/lgtm
/approve

2021-05-26 22:05 UTC, merged

2021-08-14 13:23 UTC, ArchiFleKs commented
Hi, are the pushed docker images multi arch ?

2021-08-16 21:38 UTC, pwschuurman commented
The docker image does not yet have multi arch support. Please see #586 where support is being added.