Build multi-arch images
kubernetes/node-problem-detector pull request #634
Opened 2021-12-28 14:26 UTC by glebiller

Fixes #586, Replace #588.

While trying the ARM container image from #588, I noticed that the executable inside was in the wrong architecture and creating an "exec format error".

Changes:
* Use `TARGETARCH` variable to pick the right base image in Dockerfile
* Added `build-container-amd64` and `build-container-arm64` target to Makefile
* Replace push-container target to use buildx build that push the multi-platform image to the registry

2022-01-02 17:27 UTC, glebiller commented
/assign @dchen1107

2022-01-31 17:27 UTC, glebiller commented
/assign @andyxning 
Would you please review this PR, thank you!

2022-02-01 16:09 UTC, costela commented
sorry to butt in, but maybe @Random-Liu can make good on his [offer to review](https://github.com/kubernetes/node-problem-detector/issues/586#issuecomment-869796118)? :wink:

2022-02-01 16:25 UTC, costela requested changes
Even though I can't really approve this PR, I just added some comments anyway :sweat_smile: 
Who knows? Maybe it'll get the ball rolling :wink:

2022-02-01 16:25 UTC, costela commented on Dockerfile
> +ARG TARGETARCH
```suggestion
ARG TARGETARCH
FROM k8s.gcr.io/debian-base-${TARGETARCH}:v2.0.0

ARG TARGETOS
```

AFAIK this placement [is required](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact)?

2022-02-01 16:25 UTC, costela commented on Dockerfile
> +COPY ./output/${TARGETOS}_${TARGETARCH}/bin/health-checker ${LOGCOUNTER} /home/kubernetes/bin/
AFAICS we're hardcoding `linux` in the rest of the code and not passing in `TARGETOS` as `--build-arg`. Should it maybe be removed? Or am I missing something?

2022-02-02 10:13 UTC, costela commented on Dockerfile
> +COPY ./output/${TARGETOS}_${TARGETARCH}/bin/health-checker ${LOGCOUNTER} /home/kubernetes/bin/
ah, sorry, missed the fact that `TARGETOS` is predefined by BuildKit :facepalm:

2022-02-02 10:13 UTC, costela commented on Dockerfile
> +ARG TARGETARCH
ah, sorry, missed the fact that TARGETOS is predefined by BuildKit :facepalm: 

Maybe just to clarify, for anyone - like me - trying to build with other builders like buildah?
```suggestion
FROM k8s.gcr.io/debian-base-${TARGETARCH}:v2.0.0

# pull BuildKit global vars into the build stage
ARG TARGETOS
ARG TARGETARCH
```

2022-02-07 12:51 UTC, glebiller commented
/assign @Random-Liu

2022-02-13 09:32 UTC, kelvie commented
Ah, didn't check the PRs first. I wrote another version of this in #644

2022-05-14 13:13 UTC, glebiller commented
/remove-lifecycle stale

2022-06-04 14:26 UTC, code-haven commented
I have been working on getting our Kubernetes platform to work with arm64 and it would be amazing if this can be shipped soon 🙏

2022-06-24 17:52 UTC, odidev commented
I have successfully built Node-problem-detector arm64 image locally using above made changes.  

It will be very helpful if this PR is merged, and node-problem-detector image is released.

2022-09-11 20:33 UTC, vteratipally commented
/close

2022-09-11 20:33 UTC, closed without merging