add threshold of pattern match on systemlogmonitor
kubernetes/node-problem-detector pull request #758
Opened 2023-05-25 15:05 UTC by smileusd

```release-note
This pr to add the feature on systemlogmonitor to trigger the condition only repeat match the rule pattern in a period.
For example I want add a pattern that only occur 3 times in 1 hour can trigger condition. This feature give a template for all systemlogmonitor to configure it.
If not configure them, that would be no change.
```

2023-05-25 15:06 UTC, smileusd commented
@Random-Liu PTAL

2023-05-25 16:51 UTC, mmiranda96 commented
/ok-to-test

I will take a look at this PR next week, I'm a bit swamped with other work this one.

2023-05-25 17:20 UTC, smileusd commented
@mmiranda96 Thank you trigger e2e. I will fix the test first.

2023-05-31 18:03 UTC, mmiranda96 requested changes
Thanks for your contribution. There are several points on improvement on your PR, I have left a couple of comments. Also, could you explain more in detail how your implementation works? Please update this PR description with the details.

2023-05-31 18:03 UTC, mmiranda96 commented on pkg/systemlogmonitor/counts_buffer.go
> +	for _, rule := range rules {
Going with my suggested nested config, we can add a check here:
```go
if rule.CountThresholdConfig == nil {
  continue
}
```

2023-05-31 18:03 UTC, mmiranda96 commented on pkg/systemlogmonitor/counts_buffer.go
> +		crb.data[tempIndex] = time.Now()
Also, why are we using `Now()`. Shouldn't we use the time when the log entry appeared?

2023-06-26 07:38 UTC, smileusd commented
@mmiranda96 PTAL

2023-06-29 20:30 UTC, mmiranda96 requested changes
Please address the new and previous comments. Also, please go a bit more in depth on how the feature works, why it's needed, and what are the valid use cases.

2023-06-29 20:30 UTC, mmiranda96 commented on pkg/systemlogmonitor/counts_buffer.go
> +func (crb *CountRingBuffer) IsMatchthreshold() bool {
Also, please rename to rename the function to `IsThresholdMatched`.

2023-06-29 20:30 UTC, mmiranda96 commented on pkg/systemlogmonitor/counts_buffer.go
> +		crb.data[tempIndex] = time.Now()
I'm not sure if the implementation actually depends on "now". But if it does, please consider using a clock instead, that way we can mock it in tests. See https://github.com/kubernetes/node-problem-detector/blob/fd51f17ec1f7f85086556c97b0d5efb40ead0fd6/pkg/systemlogmonitor/logwatchers/filelog/log_watcher.go#L65 for an example.

2023-06-29 20:30 UTC, mmiranda96 commented on pkg/systemlogmonitor/counts_buffer.go
> +func (crb *CountRingBuffer) IsMatchthreshold() bool {
Please add a comment explaining how this algorithm work.

2024-05-10 15:33 UTC, closed without merging