Add dependabot config and bump dependencies
kubernetes/node-problem-detector pull request #806
Opened 2023-09-08 08:11 UTC by MartinForReal

Add dependabot config and bump dependencies

2023-09-08 08:16 UTC, MartinForReal commented
/assign @mmiranda96

2023-09-08 08:16 UTC, MartinForReal commented
/assign @vteratipally

2023-09-08 09:49 UTC, hakman requested changes

2023-09-08 10:04 UTC, MartinForReal commented on .github/dependabot.yml
> +      - "approved"
yes. The dependencies will be updated if the pr passed e2e tests. And pr will be blocked if the pr is modified. (tide will remove lgtm label). In that case, reviewer need to review the pr.

2023-09-08 10:15 UTC, MartinForReal commented
/assign @hakman

2023-09-08 12:12 UTC, hakman commented on .github/dependabot.yml
> +      - "approved"
Considering the dependency on aws-sdk-go, I remember seeing endless dependabot PRs for its frequent updates.

Another option is the kOps approach, a weekly job that updates the direct dependencies, which is much less noisy with many dependencies:
https://github.com/kubernetes/kops/pull/15890
https://github.com/kubernetes/kops/blob/master/.github/workflows/update-deps.yml

2023-09-09 01:48 UTC, MartinForReal commented on .github/dependabot.yml
> +      - "approved"
I can change it to update by weekly

2023-09-09 06:54 UTC, hakman commented on .github/dependabot.yml
> +      - "approved"
I would suggest to separate the bumping of dependencies to a new PR and continue the discussion here on how and if automated dependency updates should look like.

At the moment I see these 2 options:
* dependabot that runs once a week with 5-10 open PRs at most
* script that runs once a week and does all the updates in 1 PR, but with less info on what changed

@vteratipally @mmiranda96 Any thoughts?

2023-09-14 03:04 UTC, MartinForReal commented on .github/dependabot.yml
> +      - "approved"
opened a pr for dependabot config https://github.com/kubernetes/node-problem-detector/pull/811

2023-09-14 03:19 UTC, MartinForReal commented
@hakman @vteratipally Could you please take a look? Thanks!

2023-09-14 03:35 UTC, MartinForReal commented
/retest

2023-09-14 05:06 UTC, hakman requested changes

2023-09-14 05:06 UTC, hakman commented on test/go.mod
>  	k8s.io/component-base v0.28.1
```suggestion
	k8s.io/component-base v0.28.2
```

2023-09-14 07:27 UTC, MartinForReal commented
<html>
<body>
<!--StartFragment-->

/test pull-npd-e2e-node
--


<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>

2023-09-14 14:47 UTC, hakman approved these changes

2023-09-14 14:47 UTC, hakman commented
/lgtm

2023-09-14 17:14 UTC, vteratipally commented
/lgtm
/approve

2023-09-14 18:06 UTC, merged