Add dependabot config
kubernetes/node-problem-detector pull request #811
Opened 2023-09-14 03:04 UTC by MartinForReal

2023-09-14 03:22 UTC, MartinForReal commented
/assign @hakman @vteratipally

2023-09-21 02:19 UTC, MartinForReal commented
@hakman @vteratipally Any ideas? Thanks!

2023-09-21 07:43 UTC, hakman requested changes
I would be comfortable with this with some proposed changes, but I would still leave the `lgtm` label out, so that someone can review and add /lgtm later (anyone in the org can add /lgtm).

2023-09-21 07:43 UTC, hakman commented on .github/dependabot.yml
> +    open-pull-requests-limit: 1
```suggestion
    open-pull-requests-limit: 5
```

2023-09-21 07:43 UTC, hakman commented on .github/dependabot.yml
> +      time: "01:00"
```suggestion
      interval: daily
      time: "04:00"
    rebase-strategy: "disabled"
```

2023-09-21 07:43 UTC, hakman commented on .github/dependabot.yml
> +    open-pull-requests-limit: 1
```suggestion
    open-pull-requests-limit: 5
```

2023-09-21 07:43 UTC, hakman commented on .github/dependabot.yml
> +      time: "01:00"
```suggestion
      interval: daily
      time: "04:00"
    rebase-strategy: "disabled"
```

2023-09-21 07:44 UTC, hakman commented
@vteratipally Any thoughts on this?

2023-09-21 08:04 UTC, hakman commented on .github/dependabot.yml
> +      - "lgtm"
```suggestion
```

2023-10-05 01:45 UTC, vteratipally commented
We follow the kubernetes guidelines, let me confirm with other OWNERS.

2023-10-20 01:44 UTC, MartinForReal commented
Any update would be appreciated

2023-10-24 02:32 UTC, MartinForReal commented
https://www.thoughtworks.com/en-us/radar/techniques/automatic-merging-of-dependency-update-prs @vteratipally That might be something worthy of trying out.

2024-01-04 02:32 UTC, MartinForReal commented
@vteratipally @hakman  @mmiranda96 Any advice is appreciated

2024-03-12 01:16 UTC, MartinForReal commented
/retest

2024-04-05 05:01 UTC, wangzhen127 commented
We are updating dependencies weekly now. Do we still need this?

2024-04-05 05:07 UTC, hakman commented
@wangzhen127 I think we can close this for now.
It was a good idea and debate around it. Thanks @MartinForReal!

2024-04-05 05:07 UTC, hakman commented
/close

2024-04-05 05:07 UTC, closed without merging